
services:
  web:
    build: .
    container_name: combraz
    ports:
      - "9090:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: combraz_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: combraz
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
